version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev_atravel_app
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - "9000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: ""
    depends_on:
      - mysql
    command: "php artisan serve --host=0.0.0.0"

  mysql:
    image: mysql:5.7
    container_name: dev_atravel_mysql
    restart: always
    ports:
      - "4306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: laravel

  redis:
    image: redis:alpine
    container_name: dev_atravel_redis
    restart: always
    ports:
      - "7382:6382"