version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev_atravel_app
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - "9000:8000"
    environment:
      DB_HOST: 172.17.0.1
      DB_PORT: 3306
      DB_DATABASE: ats_transfergest
      DB_USERNAME: ats_transfergest
      DB_PASSWORD: _d2fS50b!+3n4
    depends_on:
      mysql:
        condition: service_healthy
    command: "./scripts/init.sh"

  mysql:
    image: mysql:5.7
    container_name: dev_atravel_mysql
    restart: always
    ports:
      - "4306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ats_transfergest
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:alpine
    container_name: dev_atravel_redis
    restart: always
    ports:
      - "7382:6382"
