version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev_atravel_app
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - "9000:8000"
    environment:
      DB_HOST: 172.17.0.1  # Conectando ao MySQL no servidor
      DB_PORT: 3306
      DB_DATABASE: ats_transfergest
      DB_USERNAME: ats_transfergest
      DB_PASSWORD: _d2fS50b!+3n4
      REDIS_HOST: transfers.atsportugal.com  # Redis em produção
      REDIS_PORT: 6379
    command: "./scripts/init.sh"
